# Generated by Django 2.2.3 on 2019-08-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('comments', '0002_auto_20190805_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='avatar')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('is_enable', models.BooleanField(default=True, verbose_name='enabled?')),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRate',
            fields=[
                ('rate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ratings.Rate')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='movies.Movie')),
            ],
            bases=('ratings.rate',),
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Crew')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Role')),
            ],
            options={
                'unique_together': {('movie', 'crew', 'role')},
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.Comment')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
            bases=('comments.comment',),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew_list',
            field=models.ManyToManyField(through='movies.MovieCrew', to='movies.Crew'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Genre'),
        ),
    ]
